# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
unsetopt beep
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' menu select


export KEYTIMEOUT=1
bindkey -v

autoload -Uz compinit
compinit
# End of lines added by compinstall

#include the other files
#zsh config location
ZSH_CONFIG=$HOME/.config/zsh/zsh-config

[ -f $ZSH_CONFIG/env.zsh ] && source $ZSH_CONFIG/env.zsh
[ -f $ZSH_CONFIG/alias.zsh ] && source $ZSH_CONFIG/alias.zsh
[ -f $ZSH_CONFIG/theme.zsh ] && source $ZSH_CONFIG/theme.zsh

# plugins, download from github or from the AUR
PLUGIN_CONFIG=/usr/share/zsh/plugins

# https://github.com/zsh-users/zsh-autosuggestions
source $PLUGIN_CONFIG/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

# https://github.com/zsh-users/zsh-syntax-highlighting
source $PLUGIN_CONFIG/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

#source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
#source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
#source $PLUGIN_CONFIG/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# also install fzf https://github.com/junegunn/fzf
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# ~/.fzf/install
#
source /usr/share/fzf/key-bindings.zsh

# load ssh keys
#eval $(keychain --eval --quiet id_ed25519)

# load sdkman for better java sdk downloading
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"


# let make use as many threads as it likes
MAKEFLAGS="-j$(nproc)"

# zoxide need initing
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"

# pyenv needs initing too
if (( $+commands[pyenv] )); then
    export PYENV_ROOT=$HOME/.local/share/pyenv
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi
