config:
  backup: true
  create: true
  dotpath: dotfiles
  link_on_import: link
dotfiles:
  d_picom:
    link: link
    src: config/picom
    dst: ~/.config/picom
  d_awesome:
    src: config/awesome
    dst: ~/.config/awesome
    link: link
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    link: link
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
    link: link
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    link: link
profiles:
  arch-fox:
    dotfiles:
    - d_picom
    - d_awesome
    - f_zshrc
    - d_zsh
    - d_kitty
    - d_nvim
